# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1683096678);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1683098375);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1684225299);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1685052849);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.parent_directory", "C:\\Users\\X415\\Desktop\\LENGUAJE DE MARCAS\\Basilisk Portable with Flash\\User\\Basilisk\\Profiles\\Default");
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "C:\\Users\\X415\\Desktop\\LENGUAJE DE MARCAS\\Basilisk Portable with Flash\\Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.formfill.enable", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1639052896);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.migration.version", 43);
user_pref("browser.newtabpage.directory.ping", "");
user_pref("browser.newtabpage.directory.source", "");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201125140449");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2302);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20201125140449");
user_pref("browser.startup.homepage_override.mstone", "4.7.0");
user_pref("browser.startup.page", 0);
user_pref("browser.taskbar.lists.enabled", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"developer-button\",\"add-ons-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.searchSuggestionsChoice", false);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.disable_open_during_load", false);
user_pref("dom.disable_window_open_feature.location", false);
user_pref("dom.ipc.plugins.asyncdrawing.enabled", false);
user_pref("dom.ipc.plugins.flash.disable-protected-mode", true);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.9.2020.11.25");
user_pref("extensions.lastAppVersion", "52.9.2020.11.25");
user_pref("extensions.lastPlatformVersion", "4.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddon.update.url", "");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Users\\\\X415\\\\Desktop\\\\LENGUAJE DE MARCAS\\\\Basilisk Portable with Flash\\\\Bin\\\\Basilisk\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.9.2020.11.25\",\"st\":1685052756730}}}");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx.crash-guard.d3d11layers.appVersion", "52.9.2020.11.25");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x15d8");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "30.0.13044.13001");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d11video", 2);
user_pref("idle.lastDailyNotification", 1683098427);
user_pref("media.gmp-manager.buildID", "20201125140449");
user_pref("media.gmp-manager.url", "");
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.stricttransportsecurity.preloadlist", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1682583059);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.default.state", 2);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.scan.plid.all", false);
user_pref("sanity-test.device-id", "0x15d8");
user_pref("sanity-test.driver-version", "30.0.13044.13001");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20201125140449");
user_pref("security.OCSP.enabled", 0);
user_pref("security.fileuri.strict_origin_policy", false);
user_pref("security.mixed_content.send_hsts_priming", false);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1682583059);
user_pref("toolkit.startup.last_success", 1685052817);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
